[project]
name = "mast-aladin-lite"
description = "placeholder"
requires-python = ">=3.10"
authors = [
    { name = "placeholder", email = "placeholder@stsci.edu" },
]
dependencies = [
    "ipyaladin",
    "astroquery",
    "sidecar",
]

[project.urls]
Homepage = "https://mast-aladin-lite.readthedocs.io/en/latest/"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.license]
file = "LICENSE"
content-type = "text/plain"

[build-system]
requires = [
    "setuptools",
    "setuptools_scm"
]
build-backend = "setuptools.build_meta"
